### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by mhumpolec** [DouglasCAyers/salesforce-chatter-bot-feeds#2]
as I'm getting flow error An Apex error occurred: ChatterBotPostMessageInvocable.ChatterBotPostMessageException: Missing Chatter_Bot_Feeds_Setting__c.Email_Service_Address_User_ID__c. Please update custom setting with email service address for ChatterBotPostMessageEmailHandler.

I did install the Chatter Bot for Groups and set it up, this settings come with this package, so I'm unable to set it in advance :-(

**Comment by douglascayers** [comment]
Hi @mhumpolec, sorry you had trouble installing the code. You might try manually installing the code with this Salesforce CLI script, which I just tested and knows works: https://gist.github.com/douglascayers/b79523ef89ef7536053202d11a4651fb
