### ISSUE TITLE
Error when pushing message with new lines

### ISSUE THREAD

**Issue by mhumpolec** [DouglasCAyers/salesforce-chatter-bot-feeds#5]
Insert failed. First exception on row 0; first error: INVALID_MARKUP, Error while parsing Rich Text Content: Unsupported HTML tag or attribute encountered - br: [RawBody]
Class.Clowns.ChatterBotPostMessageService.postFeedItem: line 143, column 1
Class.Clowns.ChatterBotPostMessageService.postChatterMessage: line 109, column 1
Class.Clowns.ChatterBotPostMessageService.processRequest: line 78, column 1
Class.Clowns.ChatterBotPostMessageService.processRequests: line 32, column 1
Class.Clowns.ChatterBotPostMessageEmailHandler.processEmail: line 54, column 1
Class.Clowns.ChatterBotPostMessageEmailHandler.handleInboundEmail: line 22, column 1

**Comment by douglascayers** [comment]
Hi @mhumpolec,

How is the content for your post being generated?

You can use the paragraph tag with a single whitespace to force a break instead `<p>&nbsp;</p>`
