### ISSUE TITLE
Test Class Failures - Too many SOQL Queries

### ISSUE THREAD

**Issue by kbelcher83** [DouglasCAyers/salesforce-chatter-bot-feeds#6]
Hello Doug,
I'm getting apex test errors on ChatterBotPostMessageEmailHandlerTest and ChatterBotPostMessageServiceTest. I've lowered the looping from 50 to 10 and it passes fine. Are 50 iterations needed?

The email handler error is: 
System.LimitException: Too many SOQL queries: 101Stack Trace: Class.ChatterBotPostMessageService.processRequest: line 68, column 1 Class.ChatterBotPostMessageService.processRequests: line 32, column 1 Class.ChatterBotPostMessageEmailHandler.processEmail: line 54, column 1 Class.ChatterBotPostMessageEmailHandler.handleInboundEmail: line 22, column 1 Class.ChatterBotPostMessageEmailHandlerTest.test_post_messages: line 123, column 1

The post message error is: 
System.LimitException: Too many SOQL queries: 101
Stack Trace: Class.ChatterBotPostMessageService.processRequest: line 68, column 1 Class.ChatterBotPostMessageService.processRequests: line 32, column 1 Class.ChatterBotPostMessageServiceTest.test_post_messages: line 74, column 1

**Comment by douglascayers** [comment]
Hi, thanks for your interest in this project. 

No, 50 test iterations are not needed. I think I was trying to do some "bulk" testing of some kind. If for your org you need fewer, go ahead and lower the value as you did.
